is_debug: true
listen:
  type: port
  port: 2828
storage:
  host: localhost
  port: 5432
  dbname: arassachylyk
  username: postgres
  password: postgres
  sslmode: disable  
APP:
  host: localhost:2828